import { db } from '../db';
import { TEMPLATES, generateTemplate } from '../services/templateGen';
import { downloadBlob, downloadText } from '../services/exportService';
import { escapeHtml } from '../utils/escapeHtml';
import { showToast } from '../components/toast';
import { openModal, closeModal } from '../components/modal';
import type { GeneratedDoc } from '../types';

function formatDate(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

/** Convert markdown text content into a PDF blob using jsPDF. */
async function markdownToPdfBlob(content: string, title: string): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const usableWidth = pageWidth - margin * 2;
  const lineHeight = 6;
  let y = 20;

  doc.setFontSize(14);
  doc.text(title, margin, y);
  y += 12;

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text('Generated by AI Comply. Guidance only - not legal advice.', margin, y);
  doc.setTextColor(0);
  y += 10;

  doc.setFontSize(10);
  const lines = doc.splitTextToSize(content, usableWidth) as string[];
  const pageHeight = doc.internal.pageSize.getHeight();

  for (const line of lines) {
    if (y + lineHeight > pageHeight - 15) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  return doc.output('blob');
}

/** Show a generated document in a modal with download options. */
function showDocumentModal(doc: GeneratedDoc): void {
  const body = `
    <pre style="white-space:pre-wrap; max-height:60vh; overflow-y:auto; font-size:0.85rem; line-height:1.5;">${escapeHtml(doc.content)}</pre>
  `;
  const footer = `
    <div class="btn-group">
      <button class="btn btn-secondary btn-sm" id="modal-dl-md">Download as Markdown</button>
      <button class="btn btn-primary btn-sm" id="modal-dl-pdf">Download as PDF</button>
    </div>
  `;

  const modal = openModal(doc.name, body, footer);

  modal.querySelector('#modal-dl-md')?.addEventListener('click', () => {
    const filename = `${doc.templateType}-${new Date().toISOString().slice(0, 10)}.md`;
    downloadText(doc.content, filename, 'text/markdown');
    showToast('Markdown downloaded.', 'success');
  });

  modal.querySelector('#modal-dl-pdf')?.addEventListener('click', async () => {
    try {
      const pdfBlob = await markdownToPdfBlob(doc.content, doc.name);
      const filename = `${doc.templateType}-${new Date().toISOString().slice(0, 10)}.pdf`;
      downloadBlob(pdfBlob, filename);
      showToast('PDF downloaded.', 'success');
    } catch (err) {
      console.error('PDF generation failed:', err);
      showToast('Failed to generate PDF.', 'error');
    }
  });
}

/* ── Render ── */

function render(): string {
  return `
    <div class="page">
      <div class="page-header">
        <h1>Templates</h1>
        <p>Generate compliance documents from templates. Documents incorporate your company name and AI inventory.</p>
      </div>

      <div class="disclaimer-banner">
        Generated documents are for guidance only  -  they do not constitute legal advice.
        Always have compliance documents reviewed by qualified legal counsel before use.
      </div>

      <div class="stat-grid" id="template-grid"></div>

      <div class="card" id="previously-generated-section" style="margin-top:1.5rem;">
        <div class="card-header">
          <h2 class="card-title">Previously Generated</h2>
        </div>
        <div id="previously-generated-list"></div>
      </div>
    </div>`;
}

/* ── Init ── */

async function init(): Promise<void> {
  const savedDocs = await db.generatedDocs.toArray();

  // ── Build template card grid ──
  const gridEl = document.getElementById('template-grid');
  if (gridEl) {
    gridEl.innerHTML = TEMPLATES.map((t) => {
      const hasSaved = savedDocs.some((d) => d.templateType === t.id);
      return `
        <div class="card" data-template-id="${escapeHtml(t.id)}">
          <div class="card-header">
            <h3 class="card-title">${escapeHtml(t.title)}</h3>
          </div>
          <p class="text-muted text-sm">${escapeHtml(t.description)}</p>
          <div class="btn-group" style="margin-top:0.75rem;">
            <button class="btn btn-primary btn-sm" data-generate="${escapeHtml(t.id)}">Generate</button>
            ${hasSaved ? `<button class="btn btn-secondary btn-sm" data-view-saved="${escapeHtml(t.id)}">View Saved</button>` : ''}
          </div>
        </div>`;
    }).join('');

    // Attach Generate handlers
    gridEl.querySelectorAll<HTMLButtonElement>('[data-generate]').forEach((btn) => {
      btn.addEventListener('click', async () => {
        const templateId = btn.dataset.generate!;
        btn.disabled = true;
        btn.textContent = 'Generating\u2026';
        try {
          const doc = await generateTemplate(templateId);
          showToast(`"${doc.name}" generated and saved.`, 'success');
          showDocumentModal(doc);
          // Refresh the page to update saved state and previously generated list
          await refreshPreviouslyGenerated();
          await refreshGrid();
        } catch (err) {
          console.error('Template generation failed:', err);
          showToast('Failed to generate template.', 'error');
        } finally {
          btn.disabled = false;
          btn.textContent = 'Generate';
        }
      });
    });

    // Attach View Saved handlers
    gridEl.querySelectorAll<HTMLButtonElement>('[data-view-saved]').forEach((btn) => {
      btn.addEventListener('click', async () => {
        const templateId = btn.dataset.viewSaved!;
        try {
          const docs = await db.generatedDocs.where('templateType').equals(templateId).sortBy('createdAt');
          const latest = docs[docs.length - 1];
          if (latest) {
            showDocumentModal(latest);
          } else {
            showToast('No saved version found.', 'warning');
          }
        } catch (err) {
          console.error('Failed to load saved document:', err);
          showToast('Failed to load saved document.', 'error');
        }
      });
    });
  }

  // ── Previously Generated section ──
  await refreshPreviouslyGenerated();
}

async function refreshGrid(): Promise<void> {
  const savedDocs = await db.generatedDocs.toArray();
  const gridEl = document.getElementById('template-grid');
  if (!gridEl) return;

  // Update View Saved buttons visibility
  for (const t of TEMPLATES) {
    const card = gridEl.querySelector(`[data-template-id="${t.id}"]`);
    if (!card) continue;
    const btnGroup = card.querySelector('.btn-group');
    if (!btnGroup) continue;
    const hasSaved = savedDocs.some((d) => d.templateType === t.id);
    const existingBtn = btnGroup.querySelector(`[data-view-saved="${t.id}"]`);
    if (hasSaved && !existingBtn) {
      const btn = document.createElement('button');
      btn.className = 'btn btn-secondary btn-sm';
      btn.dataset.viewSaved = t.id;
      btn.textContent = 'View Saved';
      btn.addEventListener('click', async () => {
        const docs = await db.generatedDocs.where('templateType').equals(t.id).sortBy('createdAt');
        const latest = docs[docs.length - 1];
        if (latest) showDocumentModal(latest);
      });
      btnGroup.appendChild(btn);
    }
  }
}

async function refreshPreviouslyGenerated(): Promise<void> {
  const listEl = document.getElementById('previously-generated-list');
  if (!listEl) return;

  const allDocs = await db.generatedDocs.orderBy('createdAt').reverse().toArray();

  if (allDocs.length === 0) {
    listEl.innerHTML =
      '<div class="empty-state">No documents generated yet. Use the templates above to get started.</div>';
    return;
  }

  listEl.innerHTML = allDocs
    .map(
      (doc) => `
    <div class="stat-card" style="margin-bottom:0.5rem; display:flex; align-items:center; justify-content:space-between;">
      <div>
        <strong>${escapeHtml(doc.name)}</strong>
        <span class="text-muted text-sm" style="margin-left:0.5rem;">${formatDate(doc.createdAt)}</span>
      </div>
      <div class="btn-group">
        <button class="btn btn-secondary btn-sm" data-prev-view="${doc.id}">View</button>
        <button class="btn btn-secondary btn-sm" data-prev-dl-md="${doc.id}">Download .md</button>
        <button class="btn btn-primary btn-sm" data-prev-dl-pdf="${doc.id}">Download .pdf</button>
      </div>
    </div>
  `,
    )
    .join('');

  // Attach handlers
  for (const doc of allDocs) {
    listEl.querySelector(`[data-prev-view="${doc.id}"]`)?.addEventListener('click', () => {
      showDocumentModal(doc);
    });

    listEl.querySelector(`[data-prev-dl-md="${doc.id}"]`)?.addEventListener('click', () => {
      const filename = `${doc.templateType}-${doc.createdAt.slice(0, 10)}.md`;
      downloadText(doc.content, filename, 'text/markdown');
      showToast('Markdown downloaded.', 'success');
    });

    listEl.querySelector(`[data-prev-dl-pdf="${doc.id}"]`)?.addEventListener('click', async () => {
      try {
        const pdfBlob = await markdownToPdfBlob(doc.content, doc.name);
        const filename = `${doc.templateType}-${doc.createdAt.slice(0, 10)}.pdf`;
        downloadBlob(pdfBlob, filename);
        showToast('PDF downloaded.', 'success');
      } catch (err) {
        console.error('PDF generation failed:', err);
        showToast('Failed to generate PDF.', 'error');
      }
    });
  }
}

export default { render, init };
